- pipeline.id: nginx
  path.config: /usr/share/logstash/pipeline/nginx.conf

- pipeline.id: docker_info
  path.config: /usr/share/logstash/pipeline/docker_info.conf

- pipeline.id: docker_container
  path.config: /usr/share/logstash/pipeline/docker_container.conf