- pipeline.id: nginx
  path.config: /usr/share/logstash/pipeline/nginx.conf

- pipeline.id: docker_info
  path.config: /usr/share/logstash/pipeline/docker_info.conf

- pipeline.id: sonar_metrics
  path.config: /usr/share/logstash/pipeline/sonar_metrics.conf

- pipeline.id: jira_metrics
  path.config: /usr/share/logstash/pipeline/jira_metrics.conf

- pipeline.id: jenkins_metrics
  path.config: /usr/share/logstash/pipeline/jenkins_metrics.conf
